// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using apiDolar.Data;

#nullable disable

namespace apiDolar.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240607034828_MigracionExportacion")]
    partial class MigracionExportacion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("apiDolar.Models.Exportacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("fechaRegistrada")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("kilos")
                        .HasColumnType("int");

                    b.Property<string>("nombreProducto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("precioActualDolar")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("exportacion");
                });
#pragma warning restore 612, 618
        }
    }
}
